import './components/scroll';
import './components/burger';
import './components/video-join-play';
import './components/swiper';
import './components/custom-select';
import './components/modal';
import './components/modal-timer';
import './components/validate-form';
import './components/popup-message-form';
